#!/usr/bin/env bash

Downloads="$HOME/Documents/github/dlorg_nike_tornros/Downloads"

inotifywait -m -e close_write -e moved_to --format "%f" "Downloads" |
# -m = monitor, runs indefinetly, reports every event
# -e close_write, watching for the event "close_write"
# -e moved_to, watching for the event of a file being moved, i.e moving file into here, changing name
# --format "%f", only outputs filename that triggered event (not path)

while read -r filename; do
	echo "'$filename' downloaded"
done

## ADD "HAS BEEN MOVED TO"
