#!/usr/bin/env bash

# Defining the $Downloads variable, by showing where it is on the machine
Downloads="$HOME/Documents/github/dlorg_nike_tornros/Downloads"

# Creating all relevant dirs and subdirs at the same time, idempotent
mkdir -p "$Downloads"/{text,slides/{powerpoint,keynote,other},pdf/contracts,image,video,audio,code,archives,installers}

# Going trough all files present in Downloads
# ## = removing everything before the last /, to make $file shorter
for file in "$Downloads"/*; do
	filename="${file##*/}"
	
	# If filename... 
	case "$filename" in
		# File extension = *.txt etc, then:
		*.txt|*.md|*.rtf) 
			#Move to this folder
			mv "$file" "$Downloads/text/"
			;;

		# Files going into subdirectories:
		*.pptx|*.ppt|*.ppsx|*.potx)
			mv "$file" "$Downloads/slides/powerpoint"
			;; 
		*.key)
			mv "$file" "$Downloads/slides/keynote"
			;; 
		*.odp)
			mv "$file" "$Downloads/slides/other"
			;;

		# File being moved based on both prefix and file extension:
		contract_*.pdf)
			mv "$file" "$Downloads/pdf/contracts/"
			;;
		# File extension sorter must come after prefix sorter. 
		*.pdf)
			mv "$file" "$Downloads/pdf/"
			;;
 
		*.png|*.jpg|*.jpeg|*.gif|*.tiff|*.svg)
			mv "$file" "$Downloads/image/"
			;; 

		*.mov|*.mp4|*.mkv|*.avi)
			mv "$file" "$Downloads/video/"
			;; 
 
		*.mp3|*.wav|*.flac)
			mv "$file" "$Downloads/audio"
			;; 
		*.sh|*.py|*.js|*.html|*.css|*.sql)
			mv "$file" "$Downloads/code"
			;; 
		*.zip|*.7z|*.rar)
			mv "$file" "$Downloads/archives"
			;; 

		*.exe)
			mv "$file" "$Downloads/installers"
			;; 
	esac
done
