#!/usr/bin/env bash

#Defining the $Downloads variable, by showing where it is on the machine
Downloads="$HOME/Documents/github/dlorg_nike_tornros/Downloads"

#Creating all relevant dirs at the same time, idempotent
mkdir -p "$Downloads"/{text,pdf,image,video,slides,audio,code,archives,installers}
#Subfolders for slides, sorted on file-type
mkdir -p "$Downloads"/slides/{powerpoint,keynote,others}

#Going trough all files present in Downloads
# ## = removing everything before the last /, to make $file shorter
for file in "$Downloads"/*; do
	filename="${file##*/}"
	
	#If filename... 
	case "$filename" in
		#Ends on *.txt etc, then:
		*.txt|*.md|*.rtf) 
			#Move to this folder
			mv "$file" "$Downloads/text/"
			;;
		*.png|*.jpg|*.jpeg|*.gif|*.tiff|*.svg)
			mv "$file" "$Downloads/image/"
			;; 

		*.pdf)
			mv "$file" "$Downloads/pdf/"
			;; 
		*.mov|*.mp4|*.mkv|*.avi)
			mv "$file" "$Downloads/video/"
			;; 
		
		#You can make dirs within dirs to organize files even more:
		*.pptx|*.ppt|*.ppsx|*.potx)
			mv "$file" "$Downloads/slides/powerpoint"
			;; 
		*.key)
			mv "$file" "$Downloads/slides/keynote"
			;; 
		*.odp)
			mv "$file" "$Downloads/slides/others"
			;;
 
		*.mp3|*.wav|*.flac)
			mv "$file" "$Downloads/audio"
			;; 
		*.sh|*.py|*.js|*.html|*.css|*.sql)
			mv "$file" "$Downloads/code"
			;; 
		*.zip|*.7z|*.rar)
			mv "$file" "$Downloads/archives"
			;; 

		*.exe)
			mv "$file" "$Downloads/installers"
			;; 
	esac
done
